package com.cookandroid.myapplication

enum class ActivityOperation {
    SEARCH_EXPLORE,
    SEARCH_ADD,

    LIST_OF_PLAYLIST_EXPLORE,
    LIST_OF_PLAYLIST_MOVE,
    LIST_OF_PLAYLIST_SHARE,

    PLAYLIST_DETAILS_PERSONAL_TAG,
    PLAYLIST_DETAILS_GENERAL_TAG
}